import { useNavigate } from "react-router-dom";

const features = [
  { icon: "⚡", title: "AI Questions", desc: "Role-specific questions generated by Gemini in seconds." },
  { icon: "🧪", title: "Answer Evaluator", desc: "Write your answer and get scored 0–10 with detailed feedback." },
  { icon: "🎙️", title: "Simulation Mode", desc: "Timed mock interview with per-question AI scoring and a final grade." },
  { icon: "💡", title: "Concept Explainer", desc: "Deep-dive explanations for any question with one click." },
];

const LandingPage = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#fdfcfb] overflow-hidden">
      {/* Minimal top bar */}
      <header className="flex items-center justify-between px-6 py-4 max-w-6xl mx-auto">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-xl bg-orange-500 flex items-center justify-center shadow-sm">
            <span className="text-white text-sm font-bold">AI</span>
          </div>
          <span className="font-bold text-gray-900 text-[15px]">PrepAI</span>
        </div>
        <div className="flex gap-2">
          <button onClick={() => navigate("/login")} className="text-sm text-gray-600 hover:text-gray-900 px-3 py-1.5 rounded-lg hover:bg-gray-100 transition font-medium">
            Login
          </button>
          <button onClick={() => navigate("/signup")} className="text-sm bg-gray-900 hover:bg-gray-700 text-white px-4 py-1.5 rounded-lg transition font-medium">
            Get Started
          </button>
        </div>
      </header>

      {/* Hero */}
      <section className="max-w-4xl mx-auto px-6 pt-20 pb-16 text-center fade-up">
        {/* Badge */}
        <div className="inline-flex items-center gap-2 bg-orange-50 border border-orange-100 text-orange-600 text-xs font-semibold px-3 py-1 rounded-full mb-6">
          <span className="w-1.5 h-1.5 bg-orange-500 rounded-full animate-pulse" />
          Powered by Gemini AI
        </div>

        <h1 className="text-5xl sm:text-6xl font-extrabold text-gray-900 leading-[1.1] tracking-tight mb-5">
          Ace your next<br />
          <span className="text-orange-500">tech interview</span>
        </h1>
        <p className="text-gray-500 text-lg max-w-xl mx-auto mb-8 leading-relaxed">
          Generate role-specific questions, evaluate your answers with AI, and simulate real interviews — all in one place.
        </p>

        <div className="flex gap-3 justify-center flex-wrap">
          <button
            onClick={() => navigate("/signup")}
            className="bg-orange-500 hover:bg-orange-600 text-white px-7 py-3 rounded-xl font-semibold text-sm transition shadow-md shadow-orange-200 hover:shadow-orange-300"
          >
            Start for free →
          </button>
          <button
            onClick={() => navigate("/login")}
            className="bg-white border border-gray-200 hover:border-gray-400 text-gray-700 px-7 py-3 rounded-xl font-semibold text-sm transition"
          >
            Login
          </button>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-5xl mx-auto px-6 pb-24 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {features.map((f, i) => (
          <div
            key={i}
            className="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm hover:shadow-md transition hover:-translate-y-0.5 fade-up"
            style={{ animationDelay: `${i * 0.07}s` }}
          >
            <span className="text-2xl mb-3 block">{f.icon}</span>
            <p className="font-semibold text-gray-800 text-sm mb-1">{f.title}</p>
            <p className="text-gray-400 text-xs leading-relaxed">{f.desc}</p>
          </div>
        ))}
      </section>
    </div>
  );
};

export default LandingPage;
